### ISSUE TITLE
Issue after run container with init

### ISSUE THREAD

**Issue by rdaalman-ach** [savagete2860/hashicorp-vault-on-ecs-fargate#1]
curl put command for init gives back error:
`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method PUT is not allowed for this URL.</p>
</body></html>`

what can be this reason?

**Comment by savagete2860** [comment]
@rdaalman-ach you can connect Vault over the Web UI if you have that enabled to initialize Vault. I'm not sure why you'd get a 405 though unless the URI is incorrect for your deployment. My deployments werre also with Vault 1.7.3, so its possible different versions have different API paths to initilize Vault.

Are the tasks passing the target group health checks?
